config/routes.rb
Rails.application.routes.draw do

  resources :stalkees
  root 'stalkees#index'

end

app/models/stalkee.rb
class Stalkee < ActiveRecord::Base
	validates :twitter_handle, presence: true, length: {maximum: 15,minimum:5},	uniqueness: { case_sensitive: false , message: "already exists in the Twiter Handles Table"}, format: { with: /^\w+$/, multiline: true, message: "only alphabets, numbers and _ allowed"}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stalkees_controller.rb
class StalkeesController < ApplicationController
	before_action :get_stalkee, only:[:show, :edit, :update, :destroy]

	def index
		@stalkees= Stalkee.all.order("created_at DESC");
	end

	def show
		
	end

	def new
		@stalkee = Stalkee.new
	end

	def edit
	end

	def create
		@stalkee=Stalkee.new(stalkee_params)
		if @stalkee.save
			redirect_to @stalkee
		else
			render 'new'
		end
	end

	def update
		if @stalkee.update(stalkee_params)
			redirect_to @stalkee
		else
			render 'edit'
		end
	end

	def destroy
		@stalkee.destroy
		redirect_to stalkees_path
	end


	private
		def stalkee_params
			params.require(:stalkee).permit(:twitter_handle)
		end

		def get_stalkee
			@stalkee=Stalkee.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stalkees_helper.rb
module StalkeesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>TwitterStalky</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Oxygen:400,300,700' rel='stylesheet' type='text/css'>
   <link href='https://fonts.googleapis.com/css?family=Pacifico|Lobster' rel='stylesheet' type='text/css'>
  <%=favicon_link_tag "favicon" %>
</head>
<body style="text-align: center;">
<nav class="navbar navbar-default" >
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header" >
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
<!--       <img alt="Brand" src=".../assets/images/logo.jpg"> -->
     
      <%= link_to root_path,class:"navbar-brand" do %>
          <%= image_tag "logo",alt:"logo",height:"70px",width:"75px"%>
      <% end %>
       <%= link_to "@myTwitterStalky",root_path,class:"navbar-brand" %>

     <!--  <a class="navbar-brand" href="#">Twitter Stalky</a> -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="http://www.anujraajgoel.com" target="_blank">  Made with &hearts; by me </a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%= yield %>
<br><br><br><br>
<!-- footer-->
<nav class="navbar navbar-default" style="position: relative; bottom: 0; margin-bottom: 0;">
  <div class="container">
    <h2>Say, Hello! </h2>

    <ul class="list-inline">

        <li>
            <a href="https://www.facebook.com/reachtoanujraaj" class="btn-social btn-outline"><i class="fa fa-facebook-official fa-3x" aria-hidden="true"></i></a>
        </li>
        <li>
            <a href="#" class="btn-social btn-outline"><i class="fa fa-google-plus fa-3x" aria-hidden="true"></i></a>
        </li>
         <li>
             <a href="#" class="btn-social btn-outline"><i class="fa fa-twitter fa-3x" aria-hidden="true"></i></a>
        </li>
        <li>
            <a href="https://in.linkedin.com/in/anujraaj-goel-734137110" class="btn-social btn-outline" ><i class="fa fa-linkedin-square fa-3x" aria-hidden="true"></i></a>
        </li>
        <br><br>
        
    </ul>

    <section id="contact" class="map">
<div class="container">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7206.68109699593!2d81.77184240000001!3d25.426875800000012!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0000000000000000%3A0x1f0c03a031f74c3f!2sIndian+Institute+of+Information+Technology+Allahabad!5e0!3m2!1sen!2sin!4v1460300193519" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" width="100%" height="100%" frameborder="0" style="border:0" allowfullscreen>
          
        </iframe>
       </div>
    </section>
  </div>
</nav>

</body>
</html>

app/views/stalkees/_form.html.erb
<%= simple_form_for(@stalkee) do |f| %>
	<%= f.input :twitter_handle, placeholder: "Enter you Twitter Handle" %>
	<br>
	<%= f.submit class:"btn btn-success"%>
<% end %>

app/views/stalkees/edit.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Edit Twitter Handle</h1>
    <%= render 'form'%>
    <br>
    <%= link_to "Back",root_path,class:"btn btn-primary" %>
  </div>
</div>












app/views/stalkees/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="jumbotron">
    <h1>Twitter Handles</h1>
    <%= link_to 'Add New Stalkee', new_stalkee_path,class:"btn btn-success" %>
    <% @stalkees.each do |stalkee| %>
      <h1><%=link_to stalkee.twitter_handle,stalkee, target: "_blank"%></h1>
      <%= link_to "Edit",edit_stalkee_path(stalkee),class:"btn btn-primary" %>
      <!--<%= link_to "Show",stalkee,class:"btn btn-success" %>-->
      <%= link_to "Delete",stalkee,method: :delete,data:{confirm:"Are you sure"},class:"btn btn-danger" %>
    <% end %>
    
  </div>
</div>

app/views/stalkees/new.html.erb
<div class="container">
	<div class="jumbotron">
		<h1>New Twitter Handle</h1>
		<%= render 'form'%>
		<br>
		<%= link_to "Back",root_path,class:"btn btn-primary" %>
	</div>
</div>












app/views/stalkees/show.html.erb
<div class="container">
	<div class="jumbotron">
		<h1>@<%= @stalkee.twitter_handle %></h1>
		<%= link_to "Edit",edit_stalkee_path(@stalkee),class:"btn btn-primary" %>
		<%= link_to "Back",root_path,class:"btn btn-success" %>
		<%= link_to "Delete",@stalkee,method: :delete,data:{confirm:"Are you sure?"},class:"btn btn-danger" %>
		<br><br>
		<table class="table table-hover table-bordered">
			<th style="text-align: center;">Tweets</th>
			<% $client.user_timeline("gem") %>
			<% @tweets = $client.user_timeline(@stalkee.twitter_handle, include_rts: true) %>
			<% while @tweets.count > 0 do%>
				<% @tweets.each do |tweet|%>
					<tr>
					<td><%= tweet.text %></td>
					</tr>
				<% end %>
				<% last_id = @tweets.last.id %>
				<% @tweets = $client.user_timeline(@stalkee.twitter_handle, count: 200, max_id: last_id-1, include_rts: true) %>
			<% end %>
		</table>
	</div>
</div>













